---
name: build installer

on:
  push:
 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install NSIS
        shell: pwsh
        run: |
          winget install --accept-source-agreements --accept-package-agreements --disable-interactivity -e --silent --id NSIS.NSIS
      - name: print nsis version
        run: makensis /VERSION
      - name: build installer
        run: |
          dir
          makensis /V4 famitracker.nsi