---
name: build installer

on:
  push:
 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install NSIS
        shell: pwsh
        run: |
          winget install --accept-source-agreements --accept-package-agreements --disable-interactivity -e --silent --id NSIS.NSIS
      - name: print nsis version
        run: makensis /VERSION
      - name: get famitracker binary file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: http://famitracker.com/files/FamiTracker-v0.4.6.zip
          location: './src'
          sha256: 'EDC24CE14A1FC402DDB87CACDCA497EA25BB648286B879EDFC93A4E9D57AD5DC'
      - name: extract famitracker binary archive file
        run: |
          cd src
          7z x FamiTracker-v0.4.6.zip
          rm FamiTracker-v0.4.6.zip
      - name: build installer
        run: |
          dir
          dir src
          makensis /V4 famitracker.nsi
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload installer
          path: output\FamiTracker_0.4.6-setup.exe